// ─────────────────────────────────────────────────────────────────────────────
// constants/tracks.js
// Dữ liệu beats tĩnh dùng làm fallback khi chưa kết nối API
// Khi có API, dữ liệu sẽ được lấy từ MongoDB qua server
// ─────────────────────────────────────────────────────────────────────────────

export const TRACKS = [
  {
    id:          1,
    title:       'Đêm Mưa Sài Gòn',
    producer:    'BAT',
    genre:       'R&B',
    bpm:         88,
    key:         'Am',
    duration:    '3:24',
    durationSec: 204,
    tags:        ['R&B', 'Melancholic'],
    price:       29.99,
    plays:       '128K',
    color:       '#c9a96e',
    imageUrl:    '',
    audioUrl:    '',
    liked:       false,
    hot:         false,
    featured:    true,
  },
  {
    id:          2,
    title:       'Golden Hour',
    producer:    'BAT',
    genre:       'Lo-Fi',
    bpm:         92,
    key:         'Gmaj',
    duration:    '4:01',
    durationSec: 241,
    tags:        ['Lo-Fi', 'Chill'],
    price:       49.99,
    plays:       '94K',
    color:       '#e8c98a',
    imageUrl:    '',
    audioUrl:    '',
    liked:       true,
    hot:         false,
    featured:    false,
  },
  {
    id:          3,
    title:       'Hazy Autumn',
    producer:    'BAT',
    genre:       'Lo-Fi',
    bpm:         78,
    key:         'Fmaj',
    duration:    '2:58',
    durationSec: 178,
    tags:        ['Lo-Fi', 'Jazzy'],
    price:       19.99,
    plays:       '211K',
    color:       '#d4756b',
    imageUrl:    '',
    audioUrl:    '',
    liked:       false,
    hot:         true,
    featured:    false,
  },
  {
    id:          4,
    title:       'Late Night Drive',
    producer:    'BAT',
    genre:       'R&B',
    bpm:         98,
    key:         'Dm',
    duration:    '3:47',
    durationSec: 227,
    tags:        ['R&B', 'Soul'],
    price:       59.99,
    plays:       '456K',
    color:       '#a78bca',
    imageUrl:    '',
    audioUrl:    '',
    liked:       false,
    hot:         true,
    featured:    false,
  },
  {
    id:          5,
    title:       'Nostalgia Tape',
    producer:    'BAT',
    genre:       'Lo-Fi',
    bpm:         75,
    key:         'Cm',
    duration:    '3:15',
    durationSec: 195,
    tags:        ['Lo-Fi', 'Vintage'],
    price:       24.99,
    plays:       '77K',
    color:       '#7ab8a0',
    imageUrl:    '',
    audioUrl:    '',
    liked:       false,
    hot:         false,
    featured:    false,
  },
  {
    id:          6,
    title:       'Velvet Soul',
    producer:    'BAT',
    genre:       'R&B',
    bpm:         110,
    key:         'Bbmaj',
    duration:    '3:52',
    durationSec: 232,
    tags:        ['R&B', 'Smooth'],
    price:       79.99,
    plays:       '303K',
    color:       '#c9a96e',
    imageUrl:    '',
    audioUrl:    '',
    liked:       true,
    hot:         false,
    featured:    false,
  },
  {
    id:          7,
    title:       'Café Session',
    producer:    'BAT',
    genre:       'Lo-Fi',
    bpm:         82,
    key:         'Emaj',
    duration:    '2:42',
    durationSec: 162,
    tags:        ['Lo-Fi', 'Acoustic'],
    price:       34.99,
    plays:       '88K',
    color:       '#d4a574',
    imageUrl:    '',
    audioUrl:    '',
    liked:       false,
    hot:         false,
    featured:    false,
  },
  {
    id:          8,
    title:       'Midnight Bloom',
    producer:    'BAT',
    genre:       'R&B',
    bpm:         95,
    key:         'F#m',
    duration:    '4:10',
    durationSec: 250,
    tags:        ['R&B', 'Dark'],
    price:       44.99,
    plays:       '62K',
    color:       '#b07aa0',
    imageUrl:    '',
    audioUrl:    '',
    liked:       false,
    hot:         false,
    featured:    false,
  },
];
